### ISSUE TITLE
"Content" div not replaced

### ISSUE THREAD

**Issue by aawdls** [dls-controls/machine-status#17]
On the latest version I see that the "Content" string, which sould be replaced by the content, is still visible at the bottom of the page.

https://machine-status-screen.diamond.ac.uk/message

**Comment by rjwills28** [comment]
See https://github.com/dls-controls/machine-status/pull/19

**Comment by rjwills28** [comment]
Fixed with merged PR: https://github.com/dls-controls/machine-status/pull/19
