### ISSUE TITLE
Minor inconsistency in background colour

### ISSUE THREAD

**Issue by aawdls** [dls-controls/machine-status#6]
The shades of green in the textupdate widgets and the blank spaces are not quite the same

![image](https://user-images.githubusercontent.com/17617270/155172296-a64e08ef-236c-4d81-bed8-5baa6365c51a.png)

Can they be made to match?

**Comment by rjwills28** [comment]
The colour inconsistency is present in the OPI files so must have arisen during the conversion from EDM screens to OPIs. All of the darker green fields were EDM TextInput widgets and the lighter green were EDM Rectangles. I have compared the colours to the original EDM version and it looks like the lighter green is a closer match so I have converted the EDM TextInput widgets to use the lighter green as the background colour.
See PR: https://github.com/dls-controls/machine-status/pull/12

**Comment by rjwills28** [comment]
PR merged.
