### ISSUE TITLE
Change window title

### ISSUE THREAD

**Issue by aawdls** [dls-controls/machine-status#8]
Window title is still "Web display manager proto".

Please change it to Diamond Machine Status. Better, if it could also describe the current view, e.g. Week View, Day View, Front Ends, Operations Messages etc.

**Comment by rjwills28** [comment]
I have updated the default window title for the 'web' version of the machine status app to 'Diamond Machine Status'.
For the 'display' version of the machine status app I have added dynamic title which change according to the page, i.e. it wil display Day View, Week View, ... as suggested above.
See PR: https://github.com/dls-controls/machine-status/pull/9

**Comment by rjwills28** [comment]
PR merged.
